### ISSUE TITLE
Runtime Behaviorの翻訳

### ISSUE THREAD

**Issue by stzn** [stzn/swift-migration-guide-jp#14]
原文: https://github.com/apple/swift-migration-guide/blob/main/Guide.docc/RuntimeBehavior.md

**Comment by SatoTakeshiX** [comment]
@stzn san, こちら私やりたいですが、私assign権限がありませんでした。
今週中にはforkしてPull Request作れたらいいなと思ってます。
assignいただけるか、assignできる権限を 私, @SatoTakeshiXにいただけないでしょうか？

**Comment by stzn** [comment]
ありがとうございます！アサインしましたー。

**Comment by SatoTakeshiX** [comment]
ありがとうございます！
