### ISSUE TITLE
レビューの進め方についての相談

### ISSUE THREAD

**Issue by stzn** [stzn/swift-migration-guide-jp#15]

**Comment by stzn** [comment]
@treastrain さん

レビューの進め方についてご相談です。

僕の考えとしては、日本のコミュニティのみんなで作っていきたいと思っており、できる限り多くの方に見ていただきたいな思っています。(1、2人でレビューを全部やるというのがしんどいというのもあります。)

たとえば、レビュー期間を設けて輪読会などでレビューを依頼して、期限が過ぎたら最終的なApproveは、僕や @treastrain さんがやる、みたいな形などどうかなーと思ったのですが、どうでしょうか？

**Comment by treastrain** [comment]
@stzn 

提案ありがとうございます！

> たとえば、レビュー期間を設けて輪読会などでレビューを依頼して、期限が過ぎたら最終的なApproveは、僕や @treastrain さんがやる、みたいな形などどうかなーと思ったのですが、どうでしょうか？

こちら、とてもよいと思います…！
「The Swift Concurrency Migration Guide 日本語輪読会」は、[apple/swift-migration-guide](https://github.com/apple/swift-migration-guide) のドキュメント量が現時点でそこまで多くないことから、ひと通り読み切った後は更新された部分にフォーカスしたり、過去の回に参加できなかった方向けに再度読んでみたり… というような進行を想像していました（それらを何回か行ったのちにクローズかなと思っています）。

上記に「stzn/swift-migration-guide-jp をレビューしてみよう！」を加えてみたいなと感じました！

**Comment by treastrain** [comment]
ちなみに、これは私が見逃していたり聞き逃していたら大変恐縮なのですが、stzn/swift-migration-guide-jp では方針として、「原文（英語）を基本的に直訳する」のか「原文（英語）の意図を汲みつつ、意訳も行なって多くの日本語話者が自然と感じられる可能性の高い日本語にする」のかでいうと、どちらになりますか？（もしくはそれ以外の何か方針などはありますか？）

**Comment by stzn** [comment]
@treastrain さん

> 上記に「stzn/swift-migration-guide-jp をレビューしてみよう！」を加えてみたいなと感じました！

ありがとうございます！

> 「原文（英語）を基本的に直訳する」のか「原文（英語）の意図を汲みつつ、意訳も行なって多くの日本語話者が自然と感じられる可能性の高い日本語にする」のかでいうと、どちらになりますか？（もしくはそれ以外の何か方針などはありますか？）

後者のイメージです。

僕が考えるこの日本語訳の目的は、「英語のドキュメントを読むのは難しいと感じている日本語をメインにしたSwiftエンジニアが、この日本語訳を通じてSwift6へスムーズに移行を進めていけるようになる」ことだと思っています。

なので、「英語ではこう言っているけど日本語だとこっちのほうが理解しやすい」などがあれば全然変更して問題ないかなあと。

**Comment by treastrain** [comment]
> 僕が考えるこの日本語訳の目的は、「英語のドキュメントを読むのは難しいと感じている日本語をメインにしたSwiftエンジニアが、この日本語訳を通じてSwift6へスムーズに移行を進めていけるようになる」ことだと思っています。
> 
> なので、「英語ではこう言っているけど日本語だとこっちのほうが理解しやすい」などがあれば全然変更して問題ないかなあと。

承知しました！賛同します！！

**Comment by stzn** [comment]
進め方は一旦決まりましたのでCloseします。
