### ISSUE TITLE
Common Compiler Errors（2024-06-28時点まで）の翻訳

### ISSUE THREAD

**Issue by S-Shimotori** [stzn/swift-migration-guide-jp#22]
原文
https://github.com/apple/swift-migration-guide/blob/main/Guide.docc/CommonProblems.md

#3 （PR #12 ）の続きを引き続きやります🙋‍♀️

6月末時点のコミットまでを反映させるようにします（今後も本家で変更があるかもしれませんが）
https://github.com/apple/swift-migration-guide/commit/6487820801552379ffdcb2b166ca0b97c73b697a

**Comment by stzn** [comment]
ありがとうございます！

**Comment by S-Shimotori** [comment]
diff

https://github.com/apple/swift-migration-guide/compare/0d6f51d313f1e5c5f439960021b22a932ec29220...6487820801552379ffdcb2b166ca0b97c73b697a
