### ISSUE TITLE
Common Compiler Errorsの翻訳

### ISSUE THREAD

**Issue by S-Shimotori** [stzn/swift-migration-guide-jp#3]
[Common Compiler Errors](https://github.com/stzn/swift-migration-guide-jp/blob/main/Guide.docc/CommonProblems.md)の翻訳を行う

**Comment by S-Shimotori** [comment]
立候補します🙋‍♀️

**Comment by stzn** [comment]
原文: https://github.com/apple/swift-migration-guide/blob/main/Guide.docc/CommonProblems.md

**Comment by S-Shimotori** [comment]
@stzn 
相談です。
本家のCommonProblems.mdが大幅に加筆されており、

- このissueでは今swift-migration-guide-jpにある部分（ f0a9967bfb9c04b3695f7b8eece917ca25cfcf72 ）だけを翻訳し、続きを別issueで続行する
- 本家からfetchしてきてこのissueで全て対応する

いずれかの対応が必要そうです。
加筆されただけで既存の文章はあまり変わっていないので、いったん前者の対応（ #12 をreadyにする）で大丈夫かなと思ったのですがいかがでしょう

**Comment by stzn** [comment]
はい、僕はそれでOKだと思います。
@treastrain さん、どうでしょうか？

**Comment by treastrain** [comment]
メンションありがとうございます！

私も `前者の対応` で一旦よろしいかと思います…！

**Comment by stzn** [comment]
翻訳したページのトップに、どのコミットまで反映しているかを記載していただくと、どこから続きを始めればよいかが見えてよいかもしれないなと思ったのですが、どうでしょうか？

たとえば
![スクリーンショット 2024-06-17 5 17 21](https://github.com/stzn/swift-migration-guide-jp/assets/35151927/60745c83-d18a-45c3-84cc-d416c8866b6d)

**Comment by treastrain** [comment]
> 翻訳したページのトップに、どのコミットまで反映しているかを記載していただくと、どこから続きを始めればよいかが見えてよいかもしれないなと思ったのですが、どうでしょうか？

賛成です！現状だと原文のどの時点までが取り込まれているのかがわかりづらい場合が考えられますもんね…。何か diffs だけでパッとわかるようなしくみがあるのが一番ではありますが……。

**Comment by stzn** [comment]
githubで差分確認してくださいって書くのはどどうでしょうか？

たとえば

https://github.com/apple/swift-migration-guide/compare/1a734010d363947797e80b18008e3c4695e119a6%E2%80%A696249774f73d9db641c1b6daaf2894eb9dbfc63b

**Comment by treastrain** [comment]
そうですね！最も明瞭でわかりやすいです…！
