### ISSUE TITLE
Incremental Adoptionの翻訳

### ISSUE THREAD

**Issue by stzn** [stzn/swift-migration-guide-jp#5]
原文: https://github.com/apple/swift-migration-guide/blob/main/Guide.docc/IncrementalAdoption.md

希望者がいなければ↓を修正して反映します。
https://gist.github.com/stzn/0b0fb443c9e8114eac9c30581de2aebd

**Comment by S-Shimotori** [comment]
#31 が終わったらやりたいです🙋‍♀️

ですがgist上でだいぶ翻訳されてますよね
私としては、gistをベースに私が翻訳するのでも、shizさんがPRを作ってPR上で調整するのでも大丈夫です

**Comment by stzn** [comment]
@S-Shimotori さん

ありがとうございます！
gistはそこまで厳密に翻訳していないので、参考程度にしていただいて翻訳していただけるとうれしいです🙇🏻‍♂️
